gitIntegration: github_int
gitRepositoryPath: jfrog/Swampup2021-su204-cicd-deep-dive
artifactoryIntegration: artifactory_int
imageName: app_docker_image
artifactoryUrl: swampup204.jfrog.io
sourceRepository: su204-docker-staging-local
prodRepository: su204-docker-prod-local
